'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Pause,Play,RotateCw,Menu,X,BookOpen,Layers,Diamond,Compass} from 'lucide-react';
import ArcadeScene from './scene';
import {articles} from './stories';
const collection=[['7-burning-hot','7 Burning HOT','Slots','reel-design'],['777-jackpot-inferno','777 Jackpot Inferno','Slots','reel-design'],['deep-sea-predator','Deep Sea Predator','Fish games','underwater-worlds'],['buffalo-keno','Buffalo Keno','Keno','three-game-formats'],['diamond-riches','Diamond Riches','Slots','reel-design'],['fortune-lion','Fortune Lion','Slots','color-of-play'],['happy-fishing','Happy Fishing','Fish games','underwater-worlds'],['hexa-keno','Hexa Keno','Keno','three-game-formats'],['mega-money-machine','Mega Money Machine','Slots','reel-design'],['rainbow-riches','Rainbow Riches','Slots','color-of-play'],['wild-royale-gold','Wild Royale Gold','Slots','color-of-play'],['big-bass-bonzana','Big Bass Bonzana','Fish games','underwater-worlds']];
export default function Home(){
 const [motion,setMotion]=useState(false),[roll,setRoll]=useState(0),[category,setCategory]=useState('All stories'),[gameCategory,setGameCategory]=useState('All artwork'),[menu,setMenu]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setMotion(!media.matches);const change=()=>setMotion(!media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 const shown=articles.filter(a=>category==='All stories'||a.category===category),games=collection.filter(g=>gameCategory==='All artwork'||g[2]===gameCategory);
 return <div className="casino-site">
 <div className="masthead"><span>JUWA 777 · AFTERDARK EDITION</span><span>GAME WORLDS. BIG PERSONALITIES. FRESH STORIES.</span><a href="#journal">Discover the blog →</a></div>
 <header className="wrap header"><a className="brand" href="/" aria-label="Juwa Afterdark home"><img src="/art/juwa-logo.png" alt="Juwa Online" width="300" height="159"/></a><nav className={menu?'open':''} aria-label="Main navigation"><a href="#home" onClick={()=>setMenu(false)}><Compass size={17}/> Home</a><a href="#collection" onClick={()=>setMenu(false)}><Layers size={17}/> Game worlds</a><a href="#journal" onClick={()=>setMenu(false)}><BookOpen size={17}/> Blog</a><a href="#about" onClick={()=>setMenu(false)}>About</a></nav><a className="button header-link" href="#journal">Read the latest <ArrowUpRight size={17}/></a><button className="menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main>
 <section id="home" className="hero wrap"><div className="hero-copy"><p className="eyebrow">✦ WELCOME TO JUWA AFTERDARK</p><h1>ALL THE<br/><em>CASINO</em><br/>ATMOSPHERE.</h1><p className="intro">Step beyond the reels. Explore bold game worlds, colorful characters, and stories with a little extra sparkle.</p><div className="hero-actions"><a className="button" href="#collection">Explore game worlds <ArrowUpRight size={19}/></a><a className="secondary-button" href="#journal"><BookOpen size={18}/> Visit the blog</a></div><div className="hero-index"><span>THE ART</span><b>✦</b><span>THE STORIES</span><b>✦</b><span>THE AFTERDARK EDIT</span></div></div><div className="hero-stage"><div className="stage-label"><span>THE AFTERDARK MACHINE</span><span>3D SHOWCASE</span></div><ArcadeScene active={motion} roll={roll}/><div className="stage-controls"><button onClick={()=>{setMotion(true);setRoll(n=>n+1)}}><RotateCw size={16}/> Spin the scene</button><button onClick={()=>setMotion(!motion)} aria-label={motion?'Pause animations':'Resume animations'}>{motion?<Pause size={17}/>:<Play size={17}/>}</button></div></div></section>
 <section className="category-banners wrap" aria-label="Explore game categories">{[['slots-category','BEHIND THE REELS','A classic, reimagined.','Slots'],['fish-category','BENEATH THE SURFACE','Dive into another world.','Fish games'],['keno-category','A DIFFERENT KIND OF PATTERN','Numbers with personality.','Keno']].map(([img,tag,title,c])=><a key={c} href="#collection" onClick={()=>setGameCategory(c)} className={'category-banner category-'+img}><div><span>{tag}</span><h2>{title}</h2><p>Explore {c.toLowerCase()} <ArrowRight size={16}/></p></div><img src={'/art/'+img+'.png'} alt=""/></a>)}</section>
 <section className="collection wrap" id="collection"><div className="section-title"><div><p className="eyebrow"><Diamond size={15}/> THE JUWA COLLECTION</p><h2>FIND YOUR <em>WORLD.</em></h2></div><p>Explore the artwork. Discover the story.</p></div><div className="filters game-filters" aria-label="Filter game artwork">{['All artwork','Slots','Fish games','Keno'].map(c=><button key={c} className={gameCategory===c?'selected':''} aria-pressed={gameCategory===c} onClick={()=>setGameCategory(c)}>{c}</button>)}<span aria-live="polite">{games.length} covers</span></div><div className="covers">{games.map(([img,title,c,slug])=><a key={title} href={'/journal/'+slug}><div className="cover-image"><img loading="lazy" src={'/art/'+img+'.png'} alt={title+' game artwork'}/><span>Read the story <ArrowUpRight size={17}/></span></div><div><h3>{title}</h3><ArrowUpRight size={16}/></div><span>{c}</span></a>)}</div></section>
 <section className="character-feature wrap"><div><p className="eyebrow">THE CHARACTERS BEHIND THE COLOR</p><h2>A LITTLE MISCHIEF.<br/><em>A LOT OF CHARACTER.</em></h2><p>Top hats, crooked grins, and a cat that steals the scene. Meet the visual personalities in Juwa’s illustrated world.</p><a className="button" href="/journal/character-design">Meet the cast <ArrowUpRight size={18}/></a></div><img src="/art/juwa-characters.png" alt="Juwa character artwork featuring a grinning jester, a top-hatted character, a purple cat and a dog" loading="lazy"/></section>
 <section className="wrap journal" id="journal"><div className="section-title"><div><p className="eyebrow"><BookOpen size={16}/> STORIES FROM THE OTHER SIDE</p><h2>THE AFTERDARK <em>BLOG.</em></h2></div><p>A little curiosity goes a long way.</p></div><div className="filters" aria-label="Filter articles">{['All stories','Game culture','Design notes','Explainers'].map(c=><button key={c} className={category===c?'selected':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}<span aria-live="polite">{shown.length} stories</span></div><div className="stories">{shown.map(a=><a href={'/journal/'+a.slug} key={a.slug} className="story"><div className={'story-image '+(a.slug==='character-design'?'characters-image':'')}><img src={a.image} alt={a.alt} loading="lazy"/><span className="image-arrow"><ArrowUpRight/></span></div><div className="story-copy"><p className="eyebrow">{a.category} / {a.read} MIN READ</p><h3>{a.title}</h3><p>{a.description}</p><span className="read-link">Read the story <ArrowRight size={17}/></span></div></a>)}</div></section>
 <section className="about wrap" id="about"><div><div><p className="eyebrow">ABOUT THE AFTERDARK EDIT</p><h2>THE STORY DOESN’T<br/><em>STOP AT THE REELS.</em></h2></div><div><p>Juwa Afterdark is an independent blog about the art, characters, and design of casino-style games. Come for the color. Stay for a closer look.</p><a href="#journal" className="read-link">Find your next read <ArrowUpRight size={18}/></a></div></div></section>
 </main><footer className="wrap"><a className="brand" href="/"><img src="/art/juwa-logo.png" alt="Juwa Online" width="300" height="159"/></a><p>Independent editorial concept · Not an official Juwa service.<br/>Artwork and trademarks belong to their respective owners. Decorative animation only.</p><a href="#home">Back to the lobby ↑</a></footer></div>
}
