'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Pause,Play,RotateCw,BookOpen,Diamond,X} from 'lucide-react';
import dynamic from 'next/dynamic';
const ArcadeScene=dynamic(()=>import('./scene'),{ssr:false,loading:()=> <div className="three-scene scene-loading" aria-label="Loading decorative scene"/>});
import {articles} from './stories';
import {collection} from './games';
export default function Home(){
 const [motion,setMotion]=useState(false),[roll,setRoll]=useState(0),[category,setCategory]=useState('All stories'),[gameCategory,setGameCategory]=useState('All artwork'),[celebrate,setCelebrate]=useState(false),[spinning,setSpinning]=useState(false),[expanded,setExpanded]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setMotion(!media.matches);const change=()=>setMotion(!media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 const shown=articles.filter(a=>category==='All stories'||a.category===category),games=collection.filter(g=>gameCategory==='All artwork'||g[2]===gameCategory);
 return <div className="casino-site">
 <main>
 <section id="home" className="hero wrap"><div className="hero-copy"><p className="eyebrow">✦ WELCOME TO JUWA3X</p><h1>JUWA777.<br/><em>BEYOND</em><br/>THE REELS.</h1><p className="intro">The juwa777 journal: explore slots, fish games and keno through a gallery of original artwork and clear, source-based stories.</p><div className="hero-actions"><a className="button" href="/game-worlds">Explore game worlds <ArrowUpRight size={19}/></a><a className="secondary-button" href="#journal"><BookOpen size={18}/> Visit the blog</a></div><div className="hero-index"><span>THE ART</span><b>✦</b><span>THE STORIES</span><b>✦</b><span>THE JUWA3X EDIT</span></div></div><div className="hero-stage"><div className="stage-label"><span>THE JUWA3X MACHINE</span><span>3D SHOWCASE</span></div><ArcadeScene active={motion} roll={roll} onComplete={()=>{setSpinning(false);setCelebrate(true)}}/><div className="spin-hint" aria-hidden="true">✦ Give the reels a whirl ↓</div>{celebrate&&<div className="spin-celebration" role="status"><button className="dismiss-celebration" aria-label="Dismiss celebration" onClick={()=>setCelebrate(false)}><X size={18}/></button><div className="celebration-symbol"><img src="/art/Messenger_Icon_Primary_Blue.svg" alt="" width="48" height="48"/></div><strong>Yayyy! Nice spin!</strong><p>A little sparkle, just for fun.<br/>Decorative animation · No prize</p><a href="/blog">Discover your next story →</a></div>}<div className="stage-controls"><button disabled={spinning} onClick={()=>{setCelebrate(false);setSpinning(true);setMotion(true);setRoll(n=>n+1)}}><RotateCw size={16}/> {spinning?'Reels rolling…':'Roll the machine'}</button><button onClick={()=>setMotion(!motion)} aria-label={motion?'Pause animations':'Resume animations'}>{motion?<Pause size={17}/>:<Play size={17}/>}</button></div></div></section>
 <section className="category-banners wrap" aria-label="Explore game categories">{[['slots-category','BEHIND THE REELS','A classic, reimagined.','Slots'],['fish-category','BENEATH THE SURFACE','Dive into another world.','Fish games'],['keno-category','A DIFFERENT KIND OF PATTERN','Numbers with personality.','Keno']].map(([img,tag,title,c])=><a key={c} href="#collection" onClick={()=>setGameCategory(c)} className={'category-banner category-'+img}><div><span>{tag}</span><h2>{title}</h2><p>Explore {c.toLowerCase()} <ArrowRight size={16}/></p></div><img src={'/art/'+img+'.png'} alt=""/></a>)}</section>
 <section className="collection wrap" id="collection"><div className="section-title"><div><p className="eyebrow"><Diamond size={15}/> THE JUWA COLLECTION</p><h2>FIND YOUR <em>WORLD.</em></h2></div><p>Explore the artwork. Discover the story.</p></div><div className="filters game-filters" aria-label="Filter game artwork">{['All artwork','Slots','Fish games','Keno'].map(c=><button key={c} className={gameCategory===c?'selected':''} aria-pressed={gameCategory===c} onClick={()=>{setGameCategory(c);setExpanded(false)}}>{c}</button>)}<span aria-live="polite">{games.length} covers</span></div><div className="covers">{(expanded?games:games.slice(0,12)).map(([img,title,c,slug])=><a key={title} href={'/journal/'+slug}><div className="cover-image"><img loading="lazy" src={'/art/'+img+'.png'} alt={title+' game artwork'}/><span>Read the story <ArrowUpRight size={17}/></span></div><div><h3>{title}</h3><ArrowUpRight size={16}/></div><span>{c}</span></a>)}</div>{games.length>12&&<button className="button gallery-more" onClick={()=>setExpanded(!expanded)}>{expanded?"Show fewer covers":"View all "+games.length+" covers"} <ArrowRight size={17}/></button>}</section>
 <section className="character-feature wrap"><div><p className="eyebrow">THE CHARACTERS BEHIND THE COLOR</p><h2>A LITTLE MISCHIEF.<br/><em>A LOT OF CHARACTER.</em></h2><p>Top hats, crooked grins, and a cat that steals the scene. Meet the visual personalities in Juwa’s illustrated world.</p><a className="button" href="/journal/character-design">Meet the cast <ArrowUpRight size={18}/></a></div><img src="/art/juwa-characters.png" alt="Juwa character artwork featuring a grinning jester, a top-hatted character, a purple cat and a dog" loading="lazy"/></section>
 <section className="wrap journal" id="journal"><div className="section-title"><div><p className="eyebrow"><BookOpen size={16}/> STORIES FROM THE OTHER SIDE</p><h2>THE JUWA777 <em>BLOG.</em></h2></div><p>Source-based explainers. A closer look at the art.</p></div><div className="filters" aria-label="Filter articles">{['All stories','Game culture','Design notes','Explainers'].map(c=><button key={c} className={category===c?'selected':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}<span aria-live="polite">{shown.length} stories</span></div><div className="stories">{shown.map(a=><a href={'/journal/'+a.slug} key={a.slug} className="story"><div className={'story-image '+(a.slug==='character-design'?'characters-image':'')}><img src={a.image} alt={a.alt} loading="lazy"/><span className="image-arrow"><ArrowUpRight/></span></div><div className="story-copy"><p className="eyebrow">{a.category} / {a.read} MIN READ</p><h3>{a.title}</h3><p>{a.description}</p><span className="read-link">Read the story <ArrowRight size={17}/></span></div></a>)}</div></section>
 <section className="about wrap" id="about"><div><div><p className="eyebrow">ABOUT THE JUWA3X EDIT</p><h2>THE STORY DOESN’T<br/><em>STOP AT THE REELS.</em></h2></div><div><p>JUWA3X is an independent editorial blog about Juwa777 (also known as Juwa 777). Read category explainers based on the published games page, compare full-size cover artwork, and explore our visual design notes.</p><a href="#journal" className="read-link">Find your next read <ArrowUpRight size={18}/></a></div></div></section>
 </main></div>
}


