'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowRight,Pause,Play,RotateCw,Menu,X} from 'lucide-react';
import ArcadeScene from './scene';
import {articles} from './stories';
export default function Home(){
 const [motion,setMotion]=useState(false),[roll,setRoll]=useState(0),[category,setCategory]=useState('All stories'),[menu,setMenu]=useState(false);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');setMotion(!media.matches);const change=()=>setMotion(!media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change)},[]);
 const shown=articles.filter(a=>category==='All stories'||a.category===category);
 return <div><div className="masthead"><span>THE JUWA JOURNAL</span><span>GAMES, DESIGN & DISCOVERY</span><span>AFTER HOURS. FRESH PERSPECTIVES.</span></div>
 <header className="wrap header"><a className="brand" href="/" aria-label="Juwa Afterdark home">juwa<span>✦</span><small>AFTERDARK</small></a><nav className={menu?'open':''} aria-label="Main navigation"><a href="#journal" onClick={()=>setMenu(false)}>The journal</a><a href="#collection" onClick={()=>setMenu(false)}>Game collection</a><a href="#about" onClick={()=>setMenu(false)}>About</a></nav><a className="header-link" href="#journal">Find your next read <ArrowUpRight size={17}/></a><button className="menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main><section className="hero wrap"><div className="hero-copy"><p className="eyebrow">✦ THE OTHER SIDE OF PLAY</p><h1>A little spin.<br/>A different<br/><em>perspective.</em></h1><p className="intro">Step inside the world of Juwa. The games, the details, and the stories behind the screen.</p><a className="button" href="#journal">Explore the journal <ArrowUpRight size={19}/></a><div className="hero-index"><span>01 — THE AFTERDARK EDIT</span><span>SCROLL TO DISCOVER ↓</span></div></div><div className="hero-stage"><div className="stage-label"><span>JUWA / IN MOTION</span><span>INTERACTIVE 3D</span></div><ArcadeScene active={motion} roll={roll}/><div className="stage-controls"><button onClick={()=>{setMotion(true);setRoll(n=>n+1)}}><RotateCw size={16}/> Replay the animation</button><button onClick={()=>setMotion(!motion)} aria-label={motion?'Pause animations':'Resume animations'}>{motion?<Pause size={17}/>:<Play size={17}/>}</button></div></div></section>
 <div className="ribbon" aria-hidden="true"><span>BEHIND THE REELS</span><b>✦</b><span>INTO THE DEEP</span><b>✦</b><span>A CLOSER LOOK</span><b>✦</b><span>THE JUWA JOURNAL</span><b>✦</b></div>
 <section className="wrap journal" id="journal"><div className="section-title"><div><p className="eyebrow">01 / THE JOURNAL</p><h2>Worth a closer look.</h2></div><p>Fresh perspectives on a familiar world.</p></div><div className="filters" aria-label="Filter articles">{['All stories','Game culture','Design notes','Explainers'].map(c=><button key={c} className={category===c?'selected':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}<span aria-live="polite">{shown.length} stories</span></div><div className="stories">{shown.map((a,i)=><a href={'/journal/'+a.slug} key={a.slug} className={'story '+(i===0?'featured':'')}><div className="story-image"><img src={a.image} alt={a.alt} loading="lazy"/><span className="image-arrow"><ArrowUpRight/></span>{i===0&&<span className="image-label">THE EDITOR’S PICK</span>}</div><div className="story-copy"><p className="eyebrow">{a.category} / {a.read} MIN READ</p><h3>{a.title}</h3><p>{a.description}</p><span className="read-link">Read the story <ArrowRight size={17}/></span></div></a>)}</div></section>
 <section className="collection wrap" id="collection"><div className="section-title"><div><p className="eyebrow">02 / FROM THE COLLECTION</p><h2>Different worlds.<br/><em>Distinct personalities.</em></h2></div><p>A few visual worlds from your Juwa library.<br/>Select a cover to read the related story.</p></div><div className="covers">{[['7-burning-hot','7 Burning HOT','reel-design'],['deep-sea-predator','Deep Sea Predator','underwater-worlds'],['buffalo-keno','Buffalo Keno','three-game-formats'],['diamond-riches','Diamond Riches','reel-design']].map(([img,title,slug])=><a key={title} href={'/journal/'+slug}><img loading="lazy" src={'/art/'+img+'.png'} alt={title+' game cover'}/><div><h3>{title}</h3><ArrowUpRight size={18}/></div><span>Inside the artwork</span></a>)}</div></section>
 <section className="about wrap" id="about"><p className="eyebrow">03 / ABOUT AFTERDARK</p><div><h2>The story<br/><em>beyond the screen.</em></h2><div><p>Afterdark is an independent editorial concept exploring Juwa’s game imagery, visual design, and game formats. Built around the supplied Juwa collection, with room to slow down and look closer.</p><p>Our articles separate observations from claims. We don’t publish unverified payout figures, player counts, or prize promises.</p><a href="#journal" className="read-link">Back to the journal <ArrowUpRight size={18}/></a></div></div></section></main>
 <footer className="wrap"><a className="brand" href="/">juwa<span>✦</span><small>AFTERDARK</small></a><p>An independent editorial concept. Game artwork belongs to its respective owners.<br/>The homepage animation is decorative. No wagers, accounts, or prizes.</p><a href="#journal">Keep exploring ↑</a></footer></div>
}
