'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export default function ArcadeScene({active,roll,onComplete}:{active:boolean;roll:number;onComplete:()=>void}){
 const complete=useRef(onComplete);useEffect(()=>{complete.current=onComplete},[onComplete]);
 const holder=useRef<HTMLDivElement>(null),running=useRef(active),sequence=useRef(roll);const [ready,setReady]=useState(false);
 useEffect(()=>{if(!ready&&roll>0&&active){const timer=setTimeout(()=>complete.current(),3200);return()=>clearTimeout(timer)}},[ready,roll,active]);
 useEffect(()=>{running.current=active},[active]);useEffect(()=>{sequence.current=roll},[roll]);
 useEffect(()=>{const el=holder.current;if(!el)return;let renderer:THREE.WebGLRenderer;
 try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'})}catch{return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(0,1.4,8.8);camera.lookAt(0,0,0);const group=new THREE.Group();scene.add(group);group.rotation.set(.06,-.22,-.04);
 scene.add(new THREE.HemisphereLight(0xffe9c4,0x281323,3));const key=new THREE.DirectionalLight(0xffe6b2,5);key.position.set(-3,5,4);scene.add(key);const rim=new THREE.DirectionalLight(0xff3355,4);rim.position.set(4,2,1);scene.add(rim);const fill=new THREE.DirectionalLight(0xbfbaff,2);fill.position.set(-3,0,-1);scene.add(fill);
 const gold=new THREE.MeshStandardMaterial({color:0xe5b967,metalness:.78,roughness:.25}),red=new THREE.MeshStandardMaterial({color:0x6c0826,metalness:.55,roughness:.3}),black=new THREE.MeshStandardMaterial({color:0x140f16,metalness:.4,roughness:.28});const textures:THREE.Texture[]=[];
 function box(w:number,h:number,d:number,material:THREE.Material,x:number,y:number,z:number,r=.08){const mesh=new THREE.Mesh(new RoundedBoxGeometry(w,h,d,4,r),material);mesh.position.set(x,y,z);group.add(mesh);return mesh}
 box(3.05,2.18,.85,gold,0,.25,0,.16);box(2.88,2.02,.91,red,0,.25,.02,.14);box(2.7,1.35,.13,gold,0,.24,.54,.08);box(2.57,1.21,.13,black,0,.24,.62,.05);box(3.15,.26,1.03,gold,0,-.94,.06,.08);box(2.85,.12,.9,black,0,-1.1,.06,.04);
 function label(text:string,width:number,height:number,x:number,y:number,z:number){const c=document.createElement('canvas');c.width=1024;c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle='#eaca86';ctx.font='600 100px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,128);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;textures.push(t);const m=new THREE.Mesh(new THREE.PlaneGeometry(width,height),new THREE.MeshBasicMaterial({map:t,transparent:true}));m.position.set(x,y,z);group.add(m)}
 label('JUWA3X',2.04,.43,0,1.04,.51);label('THE JUWA JOURNAL',1.55,.25,0,-.62,.52);
 const reels:THREE.Mesh[]=[];
 for(let j=0;j<3;j++){const c=document.createElement('canvas');c.width=256;c.height=1024;const ctx=c.getContext('2d')!;ctx.fillStyle='#f7eed9';ctx.fillRect(0,0,256,1024);['7','◆','★','♣'].forEach((symbol,i)=>{ctx.fillStyle=i%2?'#211820':'#ae1737';ctx.font='bold 150px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(symbol,128,i*256+128)});const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.wrapT=THREE.RepeatWrapping;t.repeat.set(1,.29);t.offset.y=j*.25;textures.push(t);
 // Curved reel strips retain depth while the texture slides across each drum.
 const geometry=new THREE.PlaneGeometry(.73,1.12,1,32);const positions=geometry.attributes.position;for(let k=0;k<positions.count;k++){const y=positions.getY(k);positions.setZ(k,Math.sqrt(.36-y*y))}geometry.computeVertexNormals();const m=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({map:t,roughness:.36,metalness:.12,side:THREE.DoubleSide}));m.position.set((j-1)*.84,.23,.67);group.add(m);reels.push(m)}
 // Thin gold separators sit in front of the moving reel surfaces.
 [-.42,.42].forEach(x=>box(.045,1.18,.06,gold,x,.24,1.2,.015));
 const bulbs:THREE.Mesh[]=[];for(let i=0;i<14;i++){const mat=new THREE.MeshStandardMaterial({color:0xffdda0,emissive:0xffba42,emissiveIntensity:1});const b=new THREE.Mesh(new THREE.SphereGeometry(.035,10,8),mat);b.position.set(-1.28+i*.197,1.34,.27);group.add(b);bulbs.push(b)}
 const dice:THREE.Group[]=[];const pipGeo=new THREE.SphereGeometry(.045,12,8),pipMat=new THREE.MeshStandardMaterial({color:0x38121b,roughness:.4});
 const dots=[[[0,0]],[[-1,-1],[1,1]],[[-1,-1],[0,0],[1,1]],[[-1,-1],[1,-1],[-1,1],[1,1]],[[-1,-1],[1,-1],[0,0],[-1,1],[1,1]],[[-1,-1],[1,-1],[-1,0],[1,0],[-1,1],[1,1]]];
 for(let d=0;d<2;d++){const die=new THREE.Group();const body=new THREE.Mesh(new RoundedBoxGeometry(.62,.62,.62,4,.075),new THREE.MeshStandardMaterial({color:d?0xeec477:0xf4ebda,metalness:d?.48:.12,roughness:.26}));die.add(body);for(let face=0;face<6;face++){const side=new THREE.Group();side.rotation.set(face===2?-Math.PI/2:face===3?Math.PI/2:0,face===0?0:face===1?Math.PI:face===4?Math.PI/2:face===5?-Math.PI/2:0,0);dots[face].forEach(([x,y])=>{const pip=new THREE.Mesh(pipGeo,pipMat);pip.scale.z=.2;pip.position.set(x*.15,y*.15,.31);side.add(pip)});die.add(side)}die.position.set(d?1.55:-1.55,-1.33,d?1.1:.9);group.add(die);dice.push(die)}
 const orbit=new THREE.Mesh(new THREE.TorusGeometry(2.14,.006,6,120),new THREE.MeshBasicMaterial({color:0xbd955d,transparent:true,opacity:.26}));orbit.rotation.set(1.1,.2,.2);orbit.position.y=-.3;scene.add(orbit);
 let frame=0,last=0,time=0,elapsed=0,seen=sequence.current,reported=0,mx=0,my=0;const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.position.z=camera.aspect<1?10:8.8;camera.updateProjectionMatrix();renderer.render(scene,camera)};const observer=new ResizeObserver(resize);observer.observe(el);resize();const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();mx=(e.clientX-r.left)/r.width-.5;my=(e.clientY-r.top)/r.height-.5};el.addEventListener('pointermove',move);renderer.domElement.addEventListener('webglcontextlost',lost);
 function lost(e:Event){e.preventDefault();setReady(false)}
 const render=(now:number)=>{const dt=Math.min((now-last)/1000,.04);last=now;if(seen!==sequence.current){seen=sequence.current;elapsed=0}if(running.current&&!document.hidden){time+=dt;elapsed+=dt;group.rotation.y+=(-.22+mx*.15+Math.sin(elapsed*4)*Math.max(0,1-elapsed/3.1)*.24-group.rotation.y)*.08;group.rotation.x+=(.06+my*.08-group.rotation.x)*.04;group.position.y=Math.sin(time*.65)*.045;reels.forEach((reel,i)=>{const mat=reel.material as THREE.MeshStandardMaterial;const p=Math.min(elapsed/(2.3+i*.4),1);mat.map!.offset.y=i*.25+(1-Math.pow(1-p,3))*4});dice.forEach((die,i)=>{const p=Math.min(elapsed/(2.6+i*.25),1);const ease=1-Math.pow(1-p,3);die.rotation.set(.4+ease*Math.PI*4,.5+ease*Math.PI*(i?6:4),.2+ease*Math.PI*2);die.position.y=-1.33+Math.abs(Math.sin(p*Math.PI*3))*(1-p)*1.2});bulbs.forEach((b,i)=>{(b.material as THREE.MeshStandardMaterial).emissiveIntensity=.6+.4*Math.sin(time*3+i)});if(seen>reported&&elapsed>=3.2){reported=seen;complete.current()}renderer.render(scene,camera)}frame=requestAnimationFrame(render)};
 // Show a coherent still frame before animation starts, including reduced-motion mode.
 dice.forEach(d=>d.rotation.set(.4,.5,.2));renderer.render(scene,camera);setReady(true);frame=requestAnimationFrame(render);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('webglcontextlost',lost);scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>m.dispose())}});textures.forEach(t=>t.dispose());renderer.dispose();renderer.domElement.remove()};
 },[]);
 return <div ref={holder} className="three-scene" role="img" aria-label="Decorative three-reel machine and rolling dice">{!ready&&<div className="scene-fallback"><img src="/art/arcade-portal.webp" alt="Chrome dice in an illuminated arcade portal"/></div>}</div>
}
