'use client';
import {useEffect,useRef} from 'react';
import * as THREE from 'three';
export default function ArcadeScene({active}:{active:boolean}){
 const holder=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=holder.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'})}catch{return}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.5));el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-hidden','true');const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.z=6;const group=new THREE.Group();scene.add(group);
 const geo=new THREE.BufferGeometry();const points=new Float32Array(90*3);for(let i=0;i<90;i++){points[i*3]=Math.sin(i*7.39)*5;points[i*3+1]=Math.cos(i*2.73)*3;points[i*3+2]=Math.sin(i*1.37)*2;}geo.setAttribute('position',new THREE.BufferAttribute(points,3));const mat=new THREE.PointsMaterial({color:0xc7ff3c,size:.019,transparent:true,opacity:.75});const sparks=new THREE.Points(geo,mat);group.add(sparks);
 const ringGeo=new THREE.TorusGeometry(2.1,.004,5,120);const ringMat=new THREE.MeshBasicMaterial({color:0xb2d470,transparent:true,opacity:.22});const ring=new THREE.Mesh(ringGeo,ringMat);ring.rotation.x=1.1;ring.rotation.z=.2;group.add(ring);let mouseX=0,mouseY=0,frame=0;const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.render(scene,camera)};const observer=new ResizeObserver(resize);observer.observe(el);const move=(e:PointerEvent)=>{const r=el.getBoundingClientRect();mouseX=(e.clientX-r.left)/r.width-.5;mouseY=(e.clientY-r.top)/r.height-.5;};el.addEventListener('pointermove',move);let time=0;const render=()=>{time+=.003;group.rotation.y+=(mouseX*.13-group.rotation.y)*.04;group.rotation.x+=(-mouseY*.1-group.rotation.x)*.04;sparks.rotation.z=time*.07;ring.rotation.y=time*.2;renderer.render(scene,camera);if(active)frame=requestAnimationFrame(render)};render();return()=>{cancelAnimationFrame(frame);observer.disconnect();el.removeEventListener('pointermove',move);geo.dispose();mat.dispose();ringGeo.dispose();ringMat.dispose();renderer.dispose();renderer.domElement.remove()}},[active]);return <div ref={holder} className="three-scene" aria-hidden="true"/>;
}
