export const articles=[
{slug:'reel-design',title:'Why the reels still catch our eye.',category:'Design notes',read:3,image:'/art/7-burning-hot.png',alt:'7 Burning HOT artwork with red sevens and fiery gold details',description:'From familiar symbols to theatrical reveals: a closer look at the visual language of reel games.',sections:[['A symbol you can read in a second','A bright seven, a jewel, a simple fruit: reel artwork often uses shapes that remain recognizable at a glance. The supplied 7 Burning HOT and Diamond Riches covers illustrate two different approaches. One leans into heat and bold numerals; the other puts jewel imagery at the center.'],['Contrast does the heavy lifting','Strong outlines and highlights separate foreground symbols from a busy background. Gold against deep red gives the 7 Burning HOT cover a theatrical feel, while large lettering makes the title part of the composition. These are observations about the supplied artwork, not claims about how the game behaves.'],['Movement creates a visual rhythm','The reel-and-dice scene on this journal uses staggered stops, changing rotations, and a gentle camera perspective to explore that rhythm. It is an animation, not a playable version of a Juwa game. Its symbols do not represent a result, a reward, or a prediction.'],['Artwork is not evidence of an outcome','A vivid cover can tell you about a theme. It cannot establish fairness, payout rates, or the likelihood of any result. Those questions require specific, verifiable documentation; this journal makes no such claims.']]},
{slug:'underwater-worlds',title:'Into the blue: the art of an underwater world.',category:'Game culture',read:3,image:'/art/deep-sea-predator.png',alt:'Deep Sea Predator game artwork from the supplied Juwa library',description:'A change of scenery, a different pace. Exploring the fish-game corner of the collection.',sections:[['A different visual vocabulary','Underwater themes exchange the straight lines of reels for creatures, water, and a sense of open space. The supplied collection includes Deep Sea Predator and Happy Fishing, giving this part of the library a distinct identity.'],['Reading the cover','A cover has a small space in which to introduce its world. Notice which creature receives the most attention, how the title sits in the frame, and where the brightest areas draw your eye. Comparing covers is a useful way to see how artists build a visual hierarchy.'],['A category, not one set of rules','Juwa’s homepage lists fish shooting alongside slots and keno. That describes a broad category, rather than a guarantee that every title shares the same mechanics. A picture alone does not tell us a game’s exact controls, rules, or availability.'],['Our editorial approach','This article uses the images supplied with the local Juwa project. We discuss their presentation without inventing gameplay details, popularity rankings, or performance claims.']]},
{slug:'three-game-formats',title:'Slots, fish games, keno: three different formats.',category:'Explainers',read:3,image:'/art/buffalo-keno.png',alt:'Buffalo Keno cover art from the Juwa collection',description:'A plain-language introduction to the categories you’ll see across the library.',sections:[['Start with the category','The Juwa homepage names three game categories: slots, fish shooting, and keno. Categories can help organize a library, but they are only a starting point. Individual titles can differ, and cover art is not a complete rulebook.'],['Reel-based games','Slots use reels and symbols as their defining visual structure. In the supplied library, names such as 7 Burning HOT and Diamond Riches are paired with bold, symbol-led artwork. This journal focuses on that design language rather than offering play recommendations.'],['Fish-themed games','Fish games use underwater imagery and aquatic characters. The supplied covers include Deep Sea Predator and Happy Fishing. Their visual themes differ from traditional reel imagery, even before you open a title.'],['Keno','Keno is a number-selection and draw-based game format. Buffalo Keno and Hexa Keno appear in the supplied artwork collection. A theme or title alone cannot establish a particular game’s rules or probabilities.'],['What the collection shows','These images document a selection of titles in the supplied project. They do not establish the size of the complete catalog, current app availability, or any payout percentage. We leave those claims out rather than fill the gaps with assumptions.']]},
{slug:'reading-game-claims',title:'A better way to read a game website.',category:'Explainers',read:3,image:'/art/diamond-riches.png',alt:'Diamond Riches cover featuring jewel imagery',description:'What an image can tell you—and which claims deserve a second look.',sections:[['Separate the artwork from the evidence','An image tells a story about a theme. A statement about player numbers, testing, or availability is a factual claim. Treat them differently: enjoying an illustration does not require accepting every nearby headline.'],['Look for a source and a date','Specific figures should have a traceable source and a clear scope. Ask what was counted, when it was measured, and whether the claim applies to one title or an entire platform. Without those details, a precise-looking number may still be hard to interpret.'],['Watch for contradictory wording','If one page describes an entertainment-only experience while another mentions cash-related features, the discrepancy needs clarification. A change of terminology alone does not establish how a service actually works. This journal does not attempt to resolve that uncertainty by repeating promotional wording.'],['What to expect here','Afterdark provides short editorial articles and a visual collection. Its animated homepage has no financial outcome. We keep descriptions grounded in the supplied artwork and identify what cannot be inferred from it.']]}
];

articles.unshift(
{slug:'character-design',title:'Top hats, crooked grins & scene stealers.',category:'Game culture',read:3,image:'/art/juwa-characters.png',alt:'Illustrated Juwa characters including a grinning jester, a top-hatted figure, a purple cat and a dog',description:'Meet the mischief-makers: a closer look at the faces that give Juwa’s artwork its personality.',sections:[
['Every good cast needs a scene stealer','The purple cat is not the tallest character in this illustration. It does not wear the largest hat or occupy the center of the image. Yet that wide grin and those bright eyes make it hard to overlook. That is the fun of an ensemble picture: the eye can pick a favorite before it has read a single word.'],
['The silhouette comes first','Look at the jester’s tall, bent hat beside the rounded top hat of the character behind him. Even without their expressions, the two shapes suggest different personalities. One feels wiry and unpredictable; the other feels theatrical and self-assured. That contrast keeps a crowded illustration from turning into a collection of identical faces.'],
['Small details tell little stories','A ruff around a neck, a shiny costume, a raised hand, a knowing smile: these details invite interpretation. The dog near the front adds a softer expression to the group, while the cat’s grin provides a mischievous counterpoint. These are impressions of the artwork, rather than official character biographies. Half the pleasure is deciding what story you see in the picture.'],
['Follow the color through the cast','Purple appears in the hat, the cat, and the small figure at the lower right. Gold ties together costume details and surrounding objects. Repeated colors make the characters feel as if they belong to one illustrated world, even when their shapes are very different.'],
['Try a second look','On your next look, ignore the center and follow the edges. Notice the hands, the hats, and the direction of each gaze. An ensemble illustration rewards that slower attention: a secondary character can suddenly become the most memorable face in the scene.']
]},
{slug:'color-of-play',title:'Neon, gold & a little drama.',category:'Design notes',read:3,image:'/art/rainbow-riches.png',alt:'Rainbow Riches artwork from the Juwa collection',description:'Why a game cover feels like a tiny stage—and how color sets the mood before the title does.',sections:[
['A cover is a tiny stage','A game cover has only a small rectangle in which to establish a mood. Some reach for deep shadows and bright highlights; others fill the frame with almost every color they can fit. Across the Juwa collection, the result is a row of miniature worlds, each asking to be read in a slightly different way.'],
['Gold needs somewhere to shine','Gold feels brightest when there is something darker beside it. In cover artwork, that can mean a dark outline, a shaded background, or a deep-colored object behind the lettering. Look for those supporting areas. The highlight may get the attention, but the surrounding darkness gives it room to work.'],
['Color can connect distant details','A repeated color lets the eye move between separate parts of an image. A highlight in a title might echo a costume or an object elsewhere in the frame. On a busy cover, these little repetitions can create a sense of belonging without making every element look the same.'],
['Compare two very different worlds','Place the warm, fiery 7 Burning HOT artwork beside the aquatic Deep Sea Predator cover. Start with the dominant colors, then notice the shapes around the title. The contrast is a reminder that casino-style artwork is not a single visual formula: the theme changes the entire atmosphere.'],
['Take the slow route through the gallery','Choose one cover and look at it from a distance, then close up. Which word or shape arrives first? Which details only become visible later? The difference between those two views is where much of the craft lives. This is a visual reading of the artwork, not a claim about any game’s outcomes.']
]}
);
